name: Python CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install uv
        uv venv
        . .venv/bin/activate
        uv pip install -r development.txt

    - name: Run tests
      run: |
        . .venv/bin/activate
        python -m django test --settings=eb_sqs.test_settings
